### ISSUE TITLE
Search dropdown pushes all the courses down

### ISSUE THREAD

**Issue by tash-had** [tash-had/OptiPlan#7]
Better behaviour would be to make the dropdown overlap the courses

**Comment by tash-had** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix searchbar](https://trello.com/c/KlHzBZBV/35-fix-searchbar)

**Comment by labib-c** [comment]
[fixed here](https://github.com/tash-had/OptiPlan/pull/12)
